//
// Created by hp on 12/18/2023.
//

#ifndef LEXICAL_ANALYZER_GENERATOR_TRAILEXAMPLE_H
#define LEXICAL_ANALYZER_GENERATOR_TRAILEXAMPLE_H


class TrailExample {

};


#endif //LEXICAL_ANALYZER_GENERATOR_TRAILEXAMPLE_H
